name: CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Run lint
      run: pnpm lint
    - name: Build project
      run: pnpm run build
    - name: Upload production-ready build
      uses: actions/upload-artifact@v4
      with:
        name: dist-on-${{ matrix.node-version }}-${{ github.run_number }}-${{ github.run_id }}
        path: dist/
